// movies.js
// Your list of 40 movies, with director, runtime (min), and genre.
// Note: Anything in parentheses from your original list is intentionally ignored.

window.MOVIES = [
  { title: "Reservoir Dogs", director: "Quentin Tarantino", runtime: 99, genre: "Crime" },
  { title: "Kill Bill Vol. 1 & 2", director: "Quentin Tarantino", runtime: 247, genre: "Action" },
  { title: "The Menu", director: "Mark Mylod", runtime: 107, genre: "Thriller" },
  { title: "The Iron Claw", director: "Sean Durkin", runtime: 132, genre: "Drama" },
  { title: "Once Upon a Time in Hollywood", director: "Quentin Tarantino", runtime: 161, genre: "Comedy/Drama" },
  { title: "Starsky & Hutch", director: "Todd Phillips", runtime: 101, genre: "Comedy" },
  { title: "Django Unchained", director: "Quentin Tarantino", runtime: 165, genre: "Western" },
  { title: "The Irishman", director: "Martin Scorsese", runtime: 209, genre: "Crime" },
  { title: "Tenet", director: "Christopher Nolan", runtime: 150, genre: "Sci‑Fi" },
  { title: "Idiocracy", director: "Mike Judge", runtime: 84, genre: "Comedy" },
  { title: "Scarface", director: "Brian De Palma", runtime: 170, genre: "Crime" },
  { title: "Dodgeball", director: "Rawson Marshall Thurber", runtime: 92, genre: "Comedy" },
  { title: "The Other Guys", director: "Adam McKay", runtime: 107, genre: "Comedy" },
  { title: "Anchorman 1 & 2", director: "Adam McKay", runtime: 195, genre: "Comedy" },
  { title: "Semi‑Pro", director: "Kent Alterman", runtime: 90, genre: "Comedy" },
  { title: "Mr. & Mrs. Smith", director: "Doug Liman", runtime: 120, genre: "Action" },
  { title: "The Royal Tenenbaums", director: "Wes Anderson", runtime: 110, genre: "Comedy/Drama" },
  { title: "Mud", director: "Jeff Nichols", runtime: 130, genre: "Drama" },
  { title: "Goodfellas", director: "Martin Scorsese", runtime: 146, genre: "Crime" },
  { title: "Inglourious Basterds", director: "Quentin Tarantino", runtime: 153, genre: "War" },
  { title: "Uncut Gems", director: "Benny Safdie & Josh Safdie", runtime: 135, genre: "Thriller" },
  { title: "Rocky IV", director: "Sylvester Stallone", runtime: 91, genre: "Sports" },
  { title: "No Country for Old Men", director: "Joel Coen & Ethan Coen", runtime: 122, genre: "Thriller" },
  { title: "No Time to Die", director: "Cary Joji Fukunaga", runtime: 163, genre: "Action" },
  { title: "American Psycho", director: "Mary Harron", runtime: 102, genre: "Thriller" },
  { title: "The Northman", director: "Robert Eggers", runtime: 137, genre: "Action" },
  { title: "Zoolander", director: "Ben Stiller", runtime: 90, genre: "Comedy" },
  { title: "Forrest Gump", director: "Robert Zemeckis", runtime: 142, genre: "Drama" },
  { title: "The Gentlemen", director: "Guy Ritchie", runtime: 113, genre: "Crime" },
  { title: "Why Him?", director: "John Hamburg", runtime: 111, genre: "Comedy" },
  { title: "Spring Breakers", director: "Harmony Korine", runtime: 94, genre: "Crime" },
  { title: "The Interview", director: "Seth Rogen & Evan Goldberg", runtime: 112, genre: "Comedy" },
  { title: "Father of the Bride", director: "Charles Shyer", runtime: 105, genre: "Comedy" },
  { title: "Heat", director: "Michael Mann", runtime: 170, genre: "Crime" },
  { title: "The Internship", director: "Shawn Levy", runtime: 119, genre: "Comedy" },
  { title: "Jackie Brown", director: "Quentin Tarantino", runtime: 154, genre: "Crime" },
  { title: "Crazy, Stupid, Love", director: "Glenn Ficarra & John Requa", runtime: 118, genre: "Romance" },
  { title: "Eternal Sunshine of the Spotless Mind", director: "Michel Gondry", runtime: 108, genre: "Drama" },
];
